name: Deploy to NuGet.org

on:
  push:
    branches:
      - mainline
    tags:
      - 'release/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build and pack
        run: |
          dotnet pack --configuration Release --output ./artifacts

      - name: Publish to NuGet.org
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '5.x'

      # - name: Push package to NuGet.org
      #   run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate
